### ISSUE TITLE
App redirects to actual web browser now, defeating purpose

### ISSUE THREAD

**Issue by aburke20** [Jaxel/TheDonald.win#1]
Hey,
so last night the admins updated the way the website works, and did something with SSO and being signed in to all their split websites.

The issues is that now, whenever I open the app I get instantly kicked out and "pushed" towards my installed browser where it does an SSO authentication (or something, sorry I'm not technical) and I can then browse the website, but it's from within my browser, not within the app like has been working up until last night.

Really hope this can be an easy fix, because I have been loving using your app !

**Comment by Jaxel** [comment]
Fixed.

**Comment by aburke20** [comment]
Thanks so so much, I spend way too much time on this app and was bummed when the change messed it up. Been using it ever since you posted about it.

A million thanks to you for all the work you put into it !
